### This Drone file is being used with Drone v0.8, read documentation here:
### https://0-8-0.docs.drone.io/
aliases:
  # Using node:10 image to avoid having to install extra software as a step
  - &node-image node:10

  # When conditions
  - &when-push
    when:
      event: push
  - &when-push-on-master
    when:
      event: push
      branch: master


pipeline:
  # Runs unit tests
  unit-test:
    <<: *when-push
    image: *node-image
    commands:
      - npm ci
      - . ./aws-credentials
      - npm test
    environment:
      PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: "true"
      ENV: dev

  notify-teams-about-push-or-tag-on-master:
    image: globx/drone-plugin-teams:linux-amd64-build-1
    secrets: [ teams_webhook ]
    message_title: >
      [ ${DRONE_REPO_NAME} ]
    message_failure: >
      [ "${DRONE_BUILD_EVENT} failed" ]
    link_text: >
      [ ${DRONE_BUILD_LINK} ]
    link_url: >
      [ ${DRONE_BUILD_LINK} ]
    when:
      status: [ failure ]
      branch: [ master ]
      event: [ push, tag ]

  notify-teams-about-tag-on-hotfix:
    image: globx/drone-plugin-teams:linux-amd64-build-1
    secrets: [ teams_webhook ]
    message_title: >
      [ ${DRONE_REPO_NAME} ]
    message_failure: >
      Tag failed
    link_text: >
      [ ${DRONE_BUILD_LINK} ]
    link_url: >
      [ ${DRONE_BUILD_LINK} ]
    when:
      status: [ failure ]
      branch: [ hotfix/* ]
      event: [ tag ]

  notify-teams-about-deploy:
    image: globx/drone-plugin-teams:linux-amd64-build-1
    secrets: [ teams_webhook ]
    message_title: >
      [ ${DRONE_REPO_NAME} ]
    message_failure: >
      Deploy failed
    link_text: >
      [ ${DRONE_BUILD_LINK} ]
    link_url: >
      [ ${DRONE_BUILD_LINK} ]
    when:
      status: [ failure ]
      event: [ deploy ]